spring.application.name=Job-Portal
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/jobdetail
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#Email Properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aniketsolanke8023@gmail.com
spring.mail.password=jcozxuawurtszvxl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


jsearch.api.key=3504195dcbmsh1ee9b77a1302686p1e523ejsn28e740dbd118
jsearch.api.url=https://jsearch.p.rapidapi.com/search
jooble.api.url=https://jooble.org/api/7de15e6b-1d3f-491d-b93c-9e66780caba3
adzuna.app.id=230543aa
adzuna.app.key=736c1fea8cc7c2419acc44d177293661
adzuna.api.url.template=https://api.adzuna.com/v1/api/jobs/%s/search/1



USER_FOUND= User has registered already.
USER_NOT_FOUND= User is not registered.
INVALID_CREDENTIALS=Invalid Credentials.
OTP_NOT_FOUND=OTP is expired.
OTP_INCORRECT=OTP is incorrect.

JOB_NOT_FOUND=Job not found.
JOB_APPLIED_ALREADY=Job applied already.

jwt.secret=ZmFrZV9zZWNyZXRfa2V5X2Zvcl9qb2JfcG9ydGFsXzEyMzQ1Ng==
jwt.expiration=86400000

